# Generated by Django 2.0.6 on 2018-06-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('author', models.CharField(blank=True, default='', max_length=32, verbose_name='Author')),
                ('description', models.CharField(blank=True, default='', max_length=5120, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Api',
                'verbose_name_plural': 'Api',
            },
        ),
        migrations.CreateModel(
            name='ApiContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('OPTION', 'OPTION'), ('HEAD', 'HEAD')], max_length=8, verbose_name='Method')),
                ('params', models.CharField(blank=True, default='', max_length=510, verbose_name='Params')),
                ('body', models.CharField(blank=True, default='', max_length=2048, verbose_name='Body')),
                ('response', models.CharField(blank=True, default='', max_length=2048, verbose_name='Response')),
                ('error_response', models.CharField(blank=True, default='', max_length=2048, verbose_name='Error Response')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='document.Api', verbose_name='Api')),
            ],
            options={
                'verbose_name': 'Api Content',
                'verbose_name_plural': 'Api Content',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('author', models.CharField(blank=True, default='', max_length=32, verbose_name='Author')),
                ('description', models.CharField(blank=True, default='', max_length=5120, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('author', models.CharField(blank=True, default='', max_length=32, verbose_name='Author')),
                ('description', models.CharField(blank=True, default='', max_length=5120, verbose_name='Description')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='document.Document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Module',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_set', to='document.Document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='api',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_set', to='document.Module', verbose_name='Module'),
        ),
    ]
